import LoginPage from './LoginPage.js';
import DashboardPage from './DashboardPage.js';
import ScreenLibraryPage from './ScreenLibraryPage.js';
import ScreenPage from './ScreenPage.js';
import {
  AdminAnalyticsPage,
  AdminCoursesPage,
  AdminDashboardPage,
  AdminDepartmentsPage,
  AdminFacultyPage,
  AdminInterventionsPage,
  AdminSemestersPage,
  AdminSettingsPage,
  AdminStudentsPage,
  AdminSupportPage,
  FacultyAnalyticsPage,
  FacultyAssignmentsPage,
  FacultyAttendancePage,
  FacultyCoursesPage,
  FacultyDashboardPage,
  FacultyInterventionsPage,
  FacultyNotificationsPage,
  FacultyProfilePage,
  FacultyQuizzesPage,
  FacultyStudentDetailPage,
  FacultyStudentsPage,
  FacultySupportPage,
  StudentAssignmentsPage,
  StudentAttendancePage,
  StudentCoursesPage,
  StudentDashboardPage,
  StudentNotificationsPage,
  StudentPerformancePage,
  StudentProfilePage,
  StudentQuizzesPage,
  StudentRecommendationsPage,
  StudentStudyPlannerPage,
} from './RoleDashboardPage.js';
import { StudentSubmitAssignmentPage, FacultyGradeSubmissionPage } from './AssignmentPages.js';

export {
  LoginPage,
  DashboardPage,
  ScreenLibraryPage,
  ScreenPage,
  StudentDashboardPage,
  StudentProfilePage,
  StudentCoursesPage,
  StudentAssignmentsPage,
  StudentSubmitAssignmentPage,
  StudentQuizzesPage,
  StudentAttendancePage,
  StudentPerformancePage,
  StudentRecommendationsPage,
  StudentStudyPlannerPage,
  StudentNotificationsPage,
  FacultyDashboardPage,
  FacultyProfilePage,
  FacultyCoursesPage,
  FacultyAssignmentsPage,
  FacultyQuizzesPage,
  FacultyAttendancePage,
  FacultyStudentsPage,
  FacultyStudentDetailPage,
  FacultySupportPage,
  FacultyInterventionsPage,
  FacultyGradeSubmissionPage,
  FacultyAnalyticsPage,
  FacultyNotificationsPage,
  AdminDashboardPage,
  AdminStudentsPage,
  AdminFacultyPage,
  AdminDepartmentsPage,
  AdminCoursesPage,
  AdminSemestersPage,
  AdminAnalyticsPage,
  AdminSupportPage,
  AdminInterventionsPage,
  AdminSettingsPage,
};
